USE senac;

CREATE TABLE PRODS
(codigo			NUMERIC(3) NOT NULL,
nome			VARCHAR(50) NOT NULL,
preco			NUMERIC(5,2) NOT NULL,
tipo			CHAR(1) NULL,
-- [S]uprimento, [C]omponente, [P]eriférico
CONSTRAINT		PK1 PRIMARY KEY(codigo));

INSERT INTO PRODS
VALUES(10, 'HD', 200, 'C');
INSERT INTO PRODS
VALUES(11, 'Memoria', 250, 'C');
INSERT INTO PRODS
VALUES(12, 'Impressora', 680, 'P');
INSERT INTO PRODS
VALUES(13, 'Processador', 600, 'C');
INSERT INTO PRODS
VALUES(14, 'DVD-RW', 2, 'S');
INSERT INTO PRODS
VALUES(15, 'Papel A4', 19, 'S');
INSERT INTO PRODS
VALUES(16, 'Scanner', 199, 'P');

SELECT * FROM PRODS;

-- a)
SELECT nome FROM PRODS;

-- b)
SELECT tipo FROM PRODS;

-- c)
SELECT tipo, nome FROM PRODS;

-- d)
SELECT AVG (preco) FROM PRODS;

-- e)
SELECT AVG (preco) FROM PRODS WHERE tipo = 'S';

-- f)
SELECT AVG (preco) FROM PRODS WHERE tipo = 'S';
SELECT AVG (preco) FROM PRODS WHERE tipo = 'C';
SELECT AVG (preco) FROM PRODS WHERE tipo = 'P';
